version: '3'
services:
  node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: node1
    volumes: 
      - elasticsearch-data-1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=node1
      - cluster.name=cluster1
      - discovery.type=single-node
      - xpack.security.enabled=false
      - transport.port=9400
    networks:
      - elastic
      - kibana1
      - kibana2
    deploy:
      resources:
        limits:
          memory: 512M
  node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: node2
    volumes: 
      - elastic-data-2:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    environment:
      - node.name=node2
      - cluster.name=cluster2
      - discovery.type=single-node
      - xpack.security.enabled=false
      - transport.port=9401
    networks:
      - elastic
      - kibana2
      - kibana1
    deploy:
      resources:
        limits:
          memory: 512M
  kibana1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: kibana1
    environment:
      - ELASTICSEARCH_HOSTS=["http://node1:9200"]
    ports:
      - 5601:5601
    depends_on:
      - node1
    networks:
      - kibana1
    deploy:    
      resources:
          limits:
            cpus: '2.0'
  kibana2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: kibana2
    environment:
      - ELASTICSEARCH_HOSTS=["http://node2:9200"]
    ports:
      - 5602:5601
    depends_on:
      - node2
    networks:
      - kibana2
    deploy:    
      resources:
          limits:
            cpus: '2.0'

volumes:
  elastic-data-1:
  elastic-data-2:

networks:
  kibana1:
  kibana2:
  elastic: